server:
  port: 8080
cache: false
mybatis:
  config: classpath:Configuration.xml
  typeAliasesPackage: com.example.demo.Entity
spring:
  datasource:
    name: testdb
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema: classpath:user.sql
    data: classpath:user.data.sql
  datasource2:
    name: testdb
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema: classpath:student.sql