spring:

  datasource:

    initialization-mode: always
    one:
      driver-class-name: org.h2.Driver
      name: testdb
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: qiaomu
      password:

    two:
      name: testdb2
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb2;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: qiao
      password:


invoke:
  schema:
    location: student.sql
